### ISSUE TITLE
Mysterious error

### ISSUE THREAD

**Issue by keanemind** [keanemind/print-debugger#2]
This error is appearing during testing:
> Traceback (most recent call last):
  File "<string>", line 258, in on_continue
  File "<string>", line 430, in get_term_width
OSError: [Errno 25] Inappropriate ioctl for device

From [StackOverflow](https://stackoverflow.com/a/43141215): 

> tcgetattr: Inappropriate ioctl for device normally means that some program attempted to do a terminal control operation but its standard I/O streams weren't connected to a terminal.

It seems GDB is trying to figure out the terminal's width for its interactive display, but it fails because pipes were dup2ed to stdin and stdout.

**Comment by keanemind** [comment]
This error only appears when I am using [gdb-dashboard](https://github.com/keanemind/gdb-dashboard).
